version: '3.8'

services:
  cocheraya_db:
    image: postgis/postgis:16-3.4
    container_name: cocheraya_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cocheraya}
      POSTGRES_USER: ${POSTGRES_USER:-cocheraya_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cocheraya_pass}
      TZ: America/Lima
    ports:
      - "5432:5432"
    volumes:
      - cocheraya_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-cocheraya_user} -d ${POSTGRES_DB:-cocheraya}"]
      interval: 10s
      timeout: 5s
      retries: 5

  cocheraya_app:
    build: .
    container_name: cocheraya_app
    ports:
      - "8080:8080"
    depends_on:
      cocheraya_db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cocheraya_db:5432/cocheraya
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-cocheraya_user}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-cocheraya_pass}
      APP_JWT_SECRET: ${APP_JWT_SECRET:-cambia_este_secreto_por_uno_de_al_menos_64_caracteres_aleatorios_seguro}
      APP_JWT_EXPIRATION: ${APP_JWT_EXPIRATION:-86400000}
      CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:5173,http://localhost:8081,http://localhost:8082"
      TZ: America/Lima
      JAVA_TOOL_OPTIONS: "-Duser.timezone=America/Lima"
    restart: unless-stopped


volumes:
  cocheraya_data:
    driver: local
